// The file is automatically generated, changes will be overwritten, 
// from the mimetypes library.
//
// Copyright (c) 2023, zero.kwok@foxmail.com
// For the full copyright and license information, please view the LICENSE
// file that was distributed with this source code.

#ifndef mimetypes_h__
#define mimetypes_h__

#include <map>
#include <string>
#include <string.h>
#include <filesystem>

namespace mimetypes {
namespace detail {

    struct const_strcmp {
        bool operator()(const char* a, const char* b) const {
            return strcmp(a, b) < 0;
        }
    };

    const static std::map<const char*, const char*, const_strcmp> __mimetypes =  {
    
        // application
        { "androidproj", "application/xml" },
        { "filters", "application/xml" },
        { "vcproj", "application/xml" },
        { "vcxitems", "application/xml" },
        { "vcxproj", "application/xml" },
        { "vsprops", "application/xml" },
        { "psc1", "application/powershell" },
        { "epub", "application/epub+zip" },
        { "msepub", "application/epub+zip" },
        { "fif", "application/fractals" },
        { "hta", "application/hta" },
        { "mjs", "application/javascript" },
        { "json", "application/json" },
        { "wps", "application/kswps" },
        { "wpso", "application/kswps" },
        { "wpss", "application/kswps" },
        { "wpsx", "application/kswps" },
        { "wpt", "application/kswps" },
        { "wptx", "application/kswps" },
        { "hqx", "application/mac-binhex40" },
        { "webmanifest", "application/manifest+json" },
        { "vsi", "application/ms-vsi" },
        { "doc", "application/msword" },
        { "dot", "application/msword" },
        { "rtf", "application/msword" },
        { "wiz", "application/msword" },
        { "a", "application/octet-stream" },
        { "bin", "application/octet-stream" },
        { "o", "application/octet-stream" },
        { "obj", "application/octet-stream" },
        { "so", "application/octet-stream" },
        { "oda", "application/oda" },
        { "osdx", "application/opensearchdescription+xml" },
        { "pdf", "application/pdf" },
        { "prf", "application/pics-rules" },
        { "p10", "application/pkcs10" },
        { "p7c", "application/pkcs7-mime" },
        { "p7m", "application/pkcs7-mime" },
        { "p7s", "application/pkcs7-signature" },
        { "crl", "application/pkix-crl" },
        { "ai", "application/postscript" },
        { "eps", "application/postscript" },
        { "ps", "application/postscript" },
        { "rat", "application/rat-file" },
        { "m3u", "application/vnd.apple.mpegurl" },
        { "m3u8", "application/vnd.apple.mpegurl" },
        { "csv", "application/vnd.ms-excel" },
        { "dif", "application/vnd.ms-excel" },
        { "slk", "application/vnd.ms-excel" },
        { "xla", "application/vnd.ms-excel" },
        { "xlb", "application/vnd.ms-excel" },
        { "xlk", "application/vnd.ms-excel" },
        { "xls", "application/vnd.ms-excel" },
        { "xlt", "application/vnd.ms-excel" },
        { "xlam", "application/vnd.ms-excel.addin.macroenabled.12" },
        { "xlsb", "application/vnd.ms-excel.sheet.binary.macroenabled.12" },
        { "xlsm", "application/vnd.ms-excel.sheet.macroenabled.12" },
        { "xltm", "application/vnd.ms-excel.template.macroenabled.12" },
        { "sst", "application/vnd.ms-pki.certstore" },
        { "pko", "application/vnd.ms-pki.pko" },
        { "cat", "application/vnd.ms-pki.seccat" },
        { "pot", "application/vnd.ms-powerpoint" },
        { "ppa", "application/vnd.ms-powerpoint" },
        { "pps", "application/vnd.ms-powerpoint" },
        { "ppt", "application/vnd.ms-powerpoint" },
        { "pwz", "application/vnd.ms-powerpoint" },
        { "ppam", "application/vnd.ms-powerpoint.addin.macroenabled.12" },
        { "pptm", "application/vnd.ms-powerpoint.presentation.macroenabled.12" },
        { "sldm", "application/vnd.ms-powerpoint.slide.macroenabled.12" },
        { "ppsm", "application/vnd.ms-powerpoint.slideshow.macroenabled.12" },
        { "potm", "application/vnd.ms-powerpoint.template.macroenabled.12" },
        { "docm", "application/vnd.ms-word.document.macroenabled.12" },
        { "dotm", "application/vnd.ms-word.template.macroenabled.12" },
        { "wpl", "application/vnd.ms-wpl" },
        { "pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
        { "sldx", "application/vnd.openxmlformats-officedocument.presentationml.slide" },
        { "ppsx", "application/vnd.openxmlformats-officedocument.presentationml.slideshow" },
        { "potx", "application/vnd.openxmlformats-officedocument.presentationml.template" },
        { "xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
        { "xltx", "application/vnd.openxmlformats-officedocument.spreadsheetml.template" },
        { "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
        { "dotx", "application/vnd.openxmlformats-officedocument.wordprocessingml.template" },
        { "vsix", "application/vsix" },
        { "wasm", "application/wasm" },
        { "accountpicture-ms", "application/windows-accountpicture" },
        { "appcontent-ms", "application/windows-appcontent+xml" },
        { "library-ms", "application/windows-library+xml" },
        { "searchConnector-ms", "application/windows-search-connector+xml" },
        { "bcpio", "application/x-bcpio" },
        { "z", "application/x-compress" },
        { "tgz", "application/x-compressed" },
        { "cpio", "application/x-cpio" },
        { "dtcp-ip", "application/x-dtcp1" },
        { "dvi", "application/x-dvi" },
        { "gtar", "application/x-gtar" },
        { "gz", "application/x-gzip" },
        { "hdf", "application/x-hdf" },
        { "h5", "application/x-hdf5" },
        { "latex", "application/x-latex" },
        { "mif", "application/x-mif" },
        { "application", "application/x-ms-application" },
        { "vsto", "application/x-ms-vsto" },
        { "WMD", "application/x-ms-wmd" },
        { "wmz", "application/x-ms-wmz" },
        { "xbap", "application/x-ms-xbap" },
        { "dll", "application/x-msdownload" },
        { "exe", "application/x-msdownload" },
        { "website", "application/x-mswebsite" },
        { "cdf", "application/x-netcdf" },
        { "nc", "application/x-netcdf" },
        { "p12", "application/x-pkcs12" },
        { "pfx", "application/x-pkcs12" },
        { "p7b", "application/x-pkcs7-certificates" },
        { "spc", "application/x-pkcs7-certificates" },
        { "p7r", "application/x-pkcs7-certreqresp" },
        { "ram", "application/x-pn-realaudio" },
        { "pyc", "application/x-python-code" },
        { "pyo", "application/x-python-code" },
        { "sh", "application/x-sh" },
        { "shar", "application/x-shar" },
        { "swf", "application/x-shockwave-flash" },
        { "sit", "application/x-stuffit" },
        { "sv4cpio", "application/x-sv4cpio" },
        { "sv4crc", "application/x-sv4crc" },
        { "tar", "application/x-tar" },
        { "tcl", "application/x-tcl" },
        { "tex", "application/x-tex" },
        { "texi", "application/x-texinfo" },
        { "texinfo", "application/x-texinfo" },
        { "roff", "application/x-troff" },
        { "t", "application/x-troff" },
        { "tr", "application/x-troff" },
        { "man", "application/x-troff-man" },
        { "me", "application/x-troff-me" },
        { "ms", "application/x-troff-ms" },
        { "ustar", "application/x-ustar" },
        { "src", "application/x-wais-source" },
        { "cer", "application/x-x509-ca-cert" },
        { "crt", "application/x-x509-ca-cert" },
        { "der", "application/x-x509-ca-cert" },
        { "zip", "application/x-zip-compressed" },
        { "xaml", "application/xaml+xml" },
        { "xht", "application/xhtml+xml" },
        { "xhtml", "application/xhtml+xml" },
        { "asa", "application/xml" },
        { "asax", "application/xml" },
        { "ascx", "application/xml" },
        { "ashx", "application/xml" },
        { "asmx", "application/xml" },
        { "aspx", "application/xml" },
        { "config", "application/xml" },
        { "coverage", "application/xml" },
        { "csproj", "application/xml" },
        { "datasource", "application/xml" },
        { "dgml", "application/xml" },
        { "generictest", "application/xml" },
        { "loadtest", "application/xml" },
        { "master", "application/xml" },
        { "mtx", "application/xml" },
        { "orderedtest", "application/xml" },
        { "props", "application/xml" },
        { "psess", "application/xml" },
        { "rdf", "application/xml" },
        { "rdlc", "application/xml" },
        { "resx", "application/xml" },
        { "ruleset", "application/xml" },
        { "settings", "application/xml" },
        { "shproj", "application/xml" },
        { "sitemap", "application/xml" },
        { "skin", "application/xml" },
        { "snippet", "application/xml" },
        { "svc", "application/xml" },
        { "targets", "application/xml" },
        { "testrunconfig", "application/xml" },
        { "testsettings", "application/xml" },
        { "trx", "application/xml" },
        { "uitest", "application/xml" },
        { "vbproj", "application/xml" },
        { "vscontent", "application/xml" },
        { "vsmdi", "application/xml" },
        { "webtest", "application/xml" },
        { "wiq", "application/xml" },
        { "wsdl", "application/xml" },
        { "xdr", "application/xml" },
        { "xpdl", "application/xml" },
        { "xsc", "application/xml" },
        { "xsd", "application/xml" },
        { "xslt", "application/xml" },
        { "xss", "application/xml" },
        { "dtd", "application/xml-dtd" },
    
        // audio
        { "au", "audio/basic" },
        { "snd", "audio/basic" },
        { "ec3", "audio/ec3" },
        { "lpcm", "audio/l16" },
        { "mid", "audio/mid" },
        { "midi", "audio/mid" },
        { "rmi", "audio/mid" },
        { "m4a", "audio/mp4" },
        { "m4b", "audio/mp4" },
        { "m4p", "audio/mp4" },
        { "m4r", "audio/mp4" },
        { "mp2", "audio/mpeg" },
        { "mp3", "audio/mpeg" },
        { "mpa", "audio/mpeg" },
        { "oga", "audio/ogg" },
        { "ogg", "audio/ogg" },
        { "opus", "audio/ogg" },
        { "aac", "audio/vnd.dlna.adts" },
        { "adt", "audio/vnd.dlna.adts" },
        { "adts", "audio/vnd.dlna.adts" },
        { "ac3", "audio/vnd.dolby.dd-raw" },
        { "weba", "audio/webm" },
        { "aif", "audio/x-aiff" },
        { "aifc", "audio/x-aiff" },
        { "aiff", "audio/x-aiff" },
        { "flac", "audio/x-flac" },
        { "mka", "audio/x-matroska" },
        { "wax", "audio/x-ms-wax" },
        { "wma", "audio/x-ms-wma" },
        { "ra", "audio/x-pn-realaudio" },
        { "wav", "audio/x-wav" },
    
        // image
        { "3fr", "image/3fr" },
        { "ari", "image/ari" },
        { "arw", "image/arw" },
        { "bay", "image/bay" },
        { "cap", "image/cap" },
        { "cr2", "image/cr2" },
        { "cr3", "image/cr3" },
        { "ori", "image/cr3" },
        { "crw", "image/crw" },
        { "dcr", "image/dcr" },
        { "dcs", "image/dcs" },
        { "dng", "image/dng" },
        { "drf", "image/drf" },
        { "eip", "image/eip" },
        { "erf", "image/erf" },
        { "fff", "image/fff" },
        { "iiq", "image/iiq" },
        { "k25", "image/k25" },
        { "kdc", "image/kdc" },
        { "mef", "image/mef" },
        { "mos", "image/mos" },
        { "mrw", "image/mrw" },
        { "nef", "image/nef" },
        { "nrw", "image/nrw" },
        { "orf", "image/orf" },
        { "pef", "image/pef" },
        { "ptx", "image/ptx" },
        { "pxn", "image/pxn" },
        { "raf", "image/raf" },
        { "raw", "image/raw" },
        { "rw2", "image/rw2" },
        { "rwl", "image/rwl" },
        { "sr2", "image/sr2" },
        { "srw", "image/srw" },
        { "x3f", "image/x3f" },
        { "bmp", "image/bmp" },
        { "dib", "image/bmp" },
        { "gif", "image/gif" },
        { "ief", "image/ief" },
        { "jfif", "image/jpeg" },
        { "jpe", "image/jpeg" },
        { "jpeg", "image/jpeg" },
        { "jpg", "image/jpeg" },
        { "png", "image/png" },
        { "svg", "image/svg+xml" },
        { "tif", "image/tiff" },
        { "tiff", "image/tiff" },
        { "dds", "image/vnd.ms-dds" },
        { "jxr", "image/vnd.ms-photo" },
        { "wdp", "image/vnd.ms-photo" },
        { "ras", "image/x-cmu-raster" },
        { "emf", "image/x-emf" },
        { "ico", "image/x-icon" },
        { "pnm", "image/x-portable-anymap" },
        { "pbm", "image/x-portable-bitmap" },
        { "pgm", "image/x-portable-graymap" },
        { "ppm", "image/x-portable-pixmap" },
        { "rgb", "image/x-rgb" },
        { "wmf", "image/x-wmf" },
        { "xbm", "image/x-xbitmap" },
        { "xpm", "image/x-xpixmap" },
        { "xwd", "image/x-xwindowdump" },
    
        // message
        { "eml", "message/rfc822" },
        { "mht", "message/rfc822" },
        { "mhtml", "message/rfc822" },
        { "nws", "message/rfc822" },
    
        // text
        { "css", "text/css" },
        { "htm", "text/html" },
        { "html", "text/html" },
        { "shtml", "text/html" },
        { "XOML", "text/plain" },
        { "asm", "text/plain" },
        { "bat", "text/plain" },
        { "c", "text/plain" },
        { "cc", "text/plain" },
        { "cd", "text/plain" },
        { "cod", "text/plain" },
        { "cpp", "text/plain" },
        { "cppm", "text/plain" },
        { "cs", "text/plain" },
        { "csh", "text/plain" },
        { "cshader", "text/plain" },
        { "cur", "text/plain" },
        { "cxx", "text/plain" },
        { "dbproj", "text/plain" },
        { "def", "text/plain" },
        { "dsh", "text/plain" },
        { "dshader", "text/plain" },
        { "dsp", "text/plain" },
        { "dsw", "text/plain" },
        { "efu", "text/plain" },
        { "fx", "text/plain" },
        { "gitattributes", "text/plain" },
        { "gitignore", "text/plain" },
        { "gitmodules", "text/plain" },
        { "gsh", "text/plain" },
        { "gshader", "text/plain" },
        { "h", "text/plain" },
        { "hh", "text/plain" },
        { "hlsl", "text/plain" },
        { "hlsli", "text/plain" },
        { "hpp", "text/plain" },
        { "hsh", "text/plain" },
        { "hshader", "text/plain" },
        { "hxx", "text/plain" },
        { "i", "text/plain" },
        { "idl", "text/plain" },
        { "inc", "text/plain" },
        { "inl", "text/plain" },
        { "ipp", "text/plain" },
        { "ixx", "text/plain" },
        { "js", "text/plain" },
        { "jsproj", "text/plain" },
        { "jsx", "text/plain" },
        { "ksh", "text/plain" },
        { "lst", "text/plain" },
        { "mak", "text/plain" },
        { "map", "text/plain" },
        { "mdp", "text/plain" },
        { "mk", "text/plain" },
        { "odh", "text/plain" },
        { "odl", "text/plain" },
        { "pkgdef", "text/plain" },
        { "pkgundef", "text/plain" },
        { "pl", "text/plain" },
        { "psh", "text/plain" },
        { "pshader", "text/plain" },
        { "rc", "text/plain" },
        { "rc2", "text/plain" },
        { "rct", "text/plain" },
        { "res", "text/plain" },
        { "rgs", "text/plain" },
        { "s", "text/plain" },
        { "sln", "text/plain" },
        { "slnf", "text/plain" },
        { "srf", "text/plain" },
        { "tlh", "text/plain" },
        { "tli", "text/plain" },
        { "ts", "text/plain" },
        { "tsx", "text/plain" },
        { "tt", "text/plain" },
        { "txt", "text/plain" },
        { "user", "text/plain" },
        { "vb", "text/plain" },
        { "vcp", "text/plain" },
        { "vcw", "text/plain" },
        { "vdp", "text/plain" },
        { "vdproj", "text/plain" },
        { "vsh", "text/plain" },
        { "vshader", "text/plain" },
        { "vspscc", "text/plain" },
        { "vsscc", "text/plain" },
        { "vssscc", "text/plain" },
        { "rtx", "text/richtext" },
        { "sct", "text/scriptlet" },
        { "wsc", "text/scriptlet" },
        { "tsv", "text/tab-separated-values" },
        { "htc", "text/x-component" },
        { "contact", "text/x-ms-contact" },
        { "group", "text/x-ms-group" },
        { "iqy", "text/x-ms-iqy" },
        { "py", "text/x-python" },
        { "etx", "text/x-setext" },
        { "sgm", "text/x-sgml" },
        { "sgml", "text/x-sgml" },
        { "vcf", "text/x-vcard" },
        { "AddIn", "text/xml" },
        { "natvis", "text/xml" },
        { "vsct", "text/xml" },
        { "vsixlangpack", "text/xml" },
        { "vsixmanifest", "text/xml" },
        { "vssettings", "text/xml" },
        { "vstemplate", "text/xml" },
        { "xml", "text/xml" },
        { "xrm-ms", "text/xml" },
        { "xsl", "text/xml" },
    
        // video
        { "3gp", "video/3gpp" },
        { "3gpp", "video/3gpp" },
        { "3g2", "video/3gpp2" },
        { "3gp2", "video/3gpp2" },
        { "avi", "video/avi" },
        { "m4v", "video/mp4" },
        { "mp4", "video/mp4" },
        { "mp4v", "video/mp4" },
        { "m1v", "video/mpeg" },
        { "m2v", "video/mpeg" },
        { "mod", "video/mpeg" },
        { "mp2v", "video/mpeg" },
        { "mpe", "video/mpeg" },
        { "mpeg", "video/mpeg" },
        { "mpg", "video/mpeg" },
        { "mpv2", "video/mpeg" },
        { "tod", "video/mpeg" },
        { "ogm", "video/ogg" },
        { "ogv", "video/ogg" },
        { "ogx", "video/ogg" },
        { "mov", "video/quicktime" },
        { "qt", "video/quicktime" },
        { "uvu", "video/vnd.dece.mp4" },
        { "m2t", "video/vnd.dlna.mpeg-tts" },
        { "m2ts", "video/vnd.dlna.mpeg-tts" },
        { "mts", "video/vnd.dlna.mpeg-tts" },
        { "tts", "video/vnd.dlna.mpeg-tts" },
        { "m4u", "video/vnd.mpegurl" },
        { "webm", "video/webm" },
        { "mkv", "video/x-matroska" },
        { "asf", "video/x-ms-asf" },
        { "asx", "video/x-ms-asf" },
        { "dvr-ms", "video/x-ms-dvr" },
        { "wm", "video/x-ms-wm" },
        { "wmv", "video/x-ms-wmv" },
        { "wmx", "video/x-ms-wmx" },
        { "wvx", "video/x-ms-wvx" },
        { "movie", "video/x-sgi-movie" },
    }; // __mimetypes
} // namespace detail

inline std::string from_extension(const std::string& extension, bool strict = false)
{
    if (extension.empty())
        return strict ? "" : "application/octet-stream";

    auto _get = [&](auto name) {
        auto item = detail::__mimetypes.find(name);
        if (item != detail::__mimetypes.end())
            return item->second;
        return strict ? "" : "application/octet-stream";
    };

    if (extension[0] == '.' && extension.size() > 1)
        return _get(extension.c_str() + 1);
    else
        return _get(extension.c_str());
}

inline std::string from_filename(const std::filesystem::path& filename, bool strict = false) {
    return ::mimetypes::from_extension(filename.extension().u8string(), strict);
}

} // namespace mimetypes

#endif // mimetypes_h__
